@baseUrl = http://localhost:3000
@testEmail = admin@test.com
@testPassword = admin123


# =====================
# Auth Endpoints
# =====================

### Register a new user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}",
}

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Logout (requires login)
POST {{baseUrl}}/logout
